export interface Mod {
  id: string,
  project_id: string,
  author_id: string,
  featured: boolean,
  name: string,
  version_number: string,
  changelog: string,
  changelog_url: string | null,
  date_published: string,
  downloads: number,
  version_type: string,
  status: string,
  requested_status: string | null,
  files: {
    hashes: {sha512: string, sha1: string},
    url: string,
    filename: string,
    primary: boolean,
    size: number,
    file_type: null
  }[],
  dependencies: string[],
  game_versions: string[],
  loaders: string[],
  icon_url: string | null,
  slug: string,
  title: string,
  description: string,
  categories: string[],
  client_side: boolean,
  server_side: boolean,
  body: string,
  team: string,
  followers: number,
  published: Date,
  updated: Date,
  queryHash: string
}
